set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR armv8)

set(CMAKE_PREFIX_PATH /opt/toolchains/JetsonNano/7.3)

set(CMAKE_PROGRAM_PATH "${CMAKE_PREFIX_PATH}/bin")

set(CMAKE_C_COMPILER ${CMAKE_PREFIX_PATH}/bin/aarch64-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER ${CMAKE_PREFIX_PATH}/bin/aarch64-linux-gnu-g++)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

include_directories("${CMAKE_PREFIX_PATH}/include")

set(CMAKE_CUDA_FLAGS "-arch=sm_53 -gencode arch=compute_53,code=sm_53 -ccbin=${CMAKE_C_COMPILER}")

set(PRY_CROSS_COMPILE TRUE)
set(PRY_TARGET_JETSON_NANO TRUE)



